// src/components.rs — all ECS component types in one file.
// Small enough that splitting further would just create noise.

use crate::assets::{Handle, Mesh};

// Position in 3D world space.
pub struct Position {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

// Velocity in world units per second.
pub struct Velocity {
    pub dx: f32,
    pub dy: f32,
    pub dz: f32,
}

// RigidBody — physics simulation state.
pub struct RigidBody {
    pub velocity_x:  f32,
    pub velocity_y:  f32,
    pub _velocity_z: f32,  // Reserved for future 3D
    pub on_ground:   bool,
    pub use_gravity: bool,
}

// Collider — axis-aligned bounding box.
pub struct Collider {
    pub half_w: f32,
    pub half_h: f32,
    pub half_d: f32,  // depth for 3D

}

// Script — attaches a Lua script to an entity.
pub struct Script {
    pub path: String,
}

// Renderable — everything the renderer needs to draw an entity.
// Now carries PBR material properties directly.
pub struct Renderable {
    pub mesh:      Handle<Mesh>,

    // PBR material values.
    pub color:     [f32; 3],  // albedo / base color
    pub metallic:  f32,       // 0 = plastic, 1 = metal
    pub roughness: f32,       // 0 = mirror,  1 = matte
    pub ao:        f32,       // ambient occlusion 0..1

    // Non-uniform scale so we can make flat floors, thin walls, etc.
    // [1.0, 0.2, 10.0] = normal width, very flat, very deep
    pub scale:     [f32; 3],
}


// Health — tracks hit points for any entity that can take damage.
pub struct Health {
    pub current: i32,
    pub max:     i32,
}

impl Health {
    pub fn new(max: i32) -> Self {
        Self { current: max, max }
    }

    // is_dead() — convenience check used by both Rust and the Lua binding.
    pub fn is_dead(&self) -> bool {
        self.current <= 0
    }
}



// CollisionPair — generated by physics when two entities overlap.
#[derive(Debug, Clone)]
pub struct CollisionPair {
    pub entity_a: hecs::Entity,
    pub entity_b: hecs::Entity,
}