#![allow(dead_code)]

// src/renderer/light_probes.rs

use glam::Vec3;

/// Soft cap on how many probes the CPU grid may hold. The GPU currently
/// uploads at most 32, but the CPU grid may keep a few extra so volume
/// grids don't get silently dropped mid-edit.
pub const PROBE_CAP: usize = 64;

// IrradianceSH holds spherical harmonics coefficients for one probe.
// L1 SH (4 coefficients per color channel) captures diffuse irradiance
// from all directions without storing a full cubemap.
// 9 coefficients is the standard (L2 SH) used in UE4/Horizon.
// We use L1 (4) for simplicity — upgrade path to L2 is straightforward.
#[derive(Clone, Copy, Default)]
pub struct IrradianceSH {
    // 9 coefficients, each RGB.
    // These encode the low-frequency irradiance coming from each direction.
    // Evaluated in the shader to get the ambient light color for a given normal.
    pub coeffs: [[f32; 3]; 9],
}

// LightProbe: one capture point in the scene.
pub struct LightProbe {
    pub position:    Vec3,
    pub irradiance:  IrradianceSH,
    // Radius: how far this probe's influence extends.
    // Probes with overlapping radii blend their contributions.
    pub radius:      f32,
    // Weight: priority — higher-weighted probes dominate blends.
    pub weight:      f32,
    // Group id: 0 = ungrouped. Probes sharing a group id move together
    // when any one of them is dragged, so you can place a cluster once
    // and reposition the whole cluster as a unit.
    pub group:       u32,
    // Which probe volume generated this probe (None = placed by hand).
    // Used to rebuild only the probes owned by an edited volume.
    pub from_volume: Option<usize>,
    // Baked sky occlusion (Decima-style): fraction of the upper sky
    // hemisphere blocked by geometry at this probe (0 = open sky, 1 =
    // fully enclosed). Sampled as long-range ambient occlusion so rooms
    // and underhangs read darker than the open world, which screen-space
    // GTAO can't do. Filled by the bake; defaults to 1.0 for hand probes.
    pub sky_occlusion: f32,
}

/// A boxed probe volume (HFW-style placement). You place a box over a room
/// and it auto-fills itself with a grid of probes.
#[derive(Clone, Copy)]
pub struct ProbeVolume {
    pub center:   Vec3,
    /// Full world-space size of the box (x/y/z extents).
    pub size:     Vec3,
    /// How many cells per axis (e.g. [3, 2, 3] = 18 probes).
    pub density:  [u32; 3],
}

// LightProbeGrid manages the full set of probes and handles interpolation.
pub struct LightProbeGrid {
    pub probes: Vec<LightProbe>,
    /// User-placed probe volumes. Probes generated by a volume remember
    /// nothing extra — the volume just creates them at load/edit time.
    pub volumes: Vec<ProbeVolume>,
}

impl LightProbeGrid {
    pub fn new() -> Self {
        Self { probes: Vec::new(), volumes: Vec::new() }
    }

    // add_probe() places a probe at a world position.
    // In the editor, you'll drag these around.
    // At startup or when the scene changes, we recapture them.
    pub fn add_probe(&mut self, position: Vec3, radius: f32) {
        self.probes.push(LightProbe {
            position,
            irradiance: IrradianceSH::default(),
            radius,
            weight: 1.0,
            group: 0,
            from_volume: None,
            sky_occlusion: 1.0,
        });
    }

    // ── Probe volumes ──────────────────────────────────────────────────

    /// Adds a probe volume box and immediately populates it with a probe
    /// grid (clamped to [`PROBE_CAP`] total probes so the scene stays light).
    /// Returns the number of probes added.
    pub fn add_volume(&mut self, center: Vec3, size: Vec3, density: [u32; 3]) -> usize {
        self.volumes.push(ProbeVolume { center, size, density });
        let idx = self.volumes.len() - 1;
        let vol = self.volumes[idx];
        self.fill_volume(&vol, idx)
    }

    /// Removes a volume and every probe it generated.
    pub fn remove_volume(&mut self, idx: usize) {
        if idx >= self.volumes.len() {
            return;
        }
        self.volumes.remove(idx);
        // Remap the from_volume indices of the remaining volumes so the
        // "which volume owns me" links stay correct.
        for p in self.probes.iter_mut() {
            match p.from_volume {
                Some(v) if v == idx => p.from_volume = None,
                Some(v) if v > idx => p.from_volume = Some(v - 1),
                _ => {}
            }
        }
    }

    /// Re-populates the probes owned by volume `idx` after its box was
    /// edited. Hand-placed probes are untouched.
    pub fn repopulate_volume(&mut self, idx: usize) {
        if idx >= self.volumes.len() {
            return;
        }
        self.probes.retain(|p| p.from_volume != Some(idx));
        let vol = self.volumes[idx];
        self.fill_volume(&vol, idx);
    }

    fn fill_volume(&mut self, vol: &ProbeVolume, idx: usize) -> usize {
        let mut added = 0;
        let dx = vol.density[0].max(1);
        let dy = vol.density[1].max(1);
        let dz = vol.density[2].max(1);
        // Radius sized so neighbour probes overlap: ~1.5× the largest cell gap.
        let cell = vol.size / Vec3::new(dx as f32, dy as f32, dz as f32);
        let radius = (cell.max_element() * 1.5).clamp(1.0, 40.0);
        for x in 0..dx {
            for y in 0..dy {
                for z in 0..dz {
                    if self.probes.len() >= PROBE_CAP {
                        return added;
                    }
                    let t = Vec3::new(
                        (x as f32 + 0.5) / dx as f32,
                        (y as f32 + 0.5) / dy as f32,
                        (z as f32 + 0.5) / dz as f32,
                    );
                    let pos = vol.center + (t - Vec3::splat(0.5)) * vol.size;
                    self.probes.push(LightProbe {
                        position: pos,
                        irradiance: IrradianceSH::default(),
                        radius,
                        weight: 1.0,
                        group: 0,
                        from_volume: Some(idx),
                        sky_occlusion: 1.0,
                    });
                    added += 1;
                }
            }
        }
        added
    }

    // ── Groups ─────────────────────────────────────────────────────────

    /// Moves a probe (or, if it belongs to a group, every probe in that
    /// group) by `delta`. Dragging one probe drags its whole cluster.
    pub fn move_probe_or_group(&mut self, idx: usize, delta: Vec3) {
        if idx >= self.probes.len() {
            return;
        }
        let g = self.probes[idx].group;
        if g == 0 {
            self.probes[idx].position += delta;
        } else {
            for p in self.probes.iter_mut().filter(|p| p.group == g) {
                p.position += delta;
            }
        }
    }

    /// Assigns `group` to every probe index in `indices`.
    pub fn assign_group(&mut self, indices: &[usize], group: u32) {
        for &i in indices {
            if i < self.probes.len() {
                self.probes[i].group = group;
            }
        }
    }

    /// Smallest unused group id (skips 0 = "no group").
    pub fn next_group_id(&self) -> u32 {
        let mut next = 1u32;
        loop {
            if self.probes.iter().all(|p| p.group != next) {
                return next;
            }
            next += 1;
        }
    }

    // interpolate() returns blended SH coefficients for a world position.

    // interpolate() returns blended SH coefficients for a world position.
    // This is called once per dynamic entity per frame (very cheap).
    //
    // This implements the tetrahedral interpolation described by
    // Linfeng Zhang et al. and used in production engines.
    // For a sparse grid, it gives seamless transitions.
    pub fn interpolate(&self, position: Vec3) -> IrradianceSH {
        if self.probes.is_empty() {
            return IrradianceSH::default();
        }
        if self.probes.len() == 1 {
            return self.probes[0].irradiance;
        }

        // Step 1: Find the N nearest probes within range.
        // "Within range" = position is inside the probe's radius.
        // We collect at most 8 candidates for the blend.
        let candidates: Vec<(usize, f32)> = self.probes
            .iter()
            .enumerate()
            .filter_map(|(i, probe)| {
                let dist = (probe.position - position).length();
                if dist < probe.radius {
                    // Weight = inverse square distance × probe weight.
                    // Closer probes have much more influence.
                    // Adding a small epsilon prevents division by zero at zero distance.
                    let w = probe.weight / (dist * dist + 0.01);
                    Some((i, w))
                } else {
                    None
                }
            })
            .collect();

        // If no probes in range, fall back to the nearest probe globally.
        if candidates.is_empty() {
            let nearest = self.probes
                .iter()
                .enumerate()
                .min_by(|(_, a), (_, b)| {
                    let da = (a.position - position).length_squared();
                    let db = (b.position - position).length_squared();
                    da.partial_cmp(&db).unwrap()
                })
                .map(|(i, _)| i)
                .unwrap_or(0);
            return self.probes[nearest].irradiance;
        }

        // Step 2: Tetrahedral interpolation among candidates.
        //
        // True tetrahedral interpolation requires finding the containing
        // tetrahedron and computing barycentric coordinates.
        // For a production engine you'd precompute the Delaunay triangulation
        // of all probe positions at level load time.
        //
        // Our approximation: weighted blend using inverse distance weighting (IDW)
        // with the distance falloff shaped like a smooth cubic fade.
        // This gives C1 continuity (smooth first derivative = no popping).
        //
        // The cubic fade: f(t) = 1 - 3t² + 2t³ (standard smoothstep).
        // At t=0 (probe center): weight = 1.0
        // At t=1 (probe edge):   weight = 0.0
        // First derivative is 0 at both ends — smooth entry and exit.
        let total_weight: f32 = candidates.iter().map(|(_, w)| w).sum();

        if total_weight < 0.0001 {
            return self.probes[candidates[0].0].irradiance;
        }

        // Accumulate weighted SH coefficients.
        let mut blended = IrradianceSH::default();

        for (probe_idx, raw_weight) in &candidates {
            let probe    = &self.probes[*probe_idx];
            let dist     = (probe.position - position).length();
            // t: 0 at probe center, 1 at probe edge.
            let t        = (dist / probe.radius).clamp(0.0, 1.0);
            // Cubic smoothstep: smooth entry AND exit.
            // This is what makes transitions invisible — no linear kink at the edge.
            let smoothed = 1.0 - t * t * (3.0 - 2.0 * t);
            let w        = raw_weight * smoothed / total_weight;

            for c in 0..9 {
                blended.coeffs[c][0] += probe.irradiance.coeffs[c][0] * w;
                blended.coeffs[c][1] += probe.irradiance.coeffs[c][1] * w;
                blended.coeffs[c][2] += probe.irradiance.coeffs[c][2] * w;
            }
        }

        blended
    }

    // sample_sh() evaluates the SH in a given direction.
    // Called in the shader using pre-uploaded coefficients per entity.
    // This replaces the simple ambient term with directional ambient.
    //
    // direction: the surface normal direction (normalized).
    // Returns: irradiance color arriving from that direction.
    pub fn evaluate_sh(sh: &IrradianceSH, direction: Vec3) -> Vec3 {
        let d = direction.normalize();

        // L0 (constant) + L1 (linear) SH basis evaluation.
        // The constant factors (0.282095, 0.488603) are the SH basis
        // function values for the first two bands.
        // Full formula from "An Efficient Representation for Irradiance
        // Environment Maps" (Ramamoorthi & Hanrahan 2001).
        let mut result = Vec3::ZERO;

        // Band 0: constant ambient
        result += Vec3::from(sh.coeffs[0]) * 0.282095;

        // Band 1: linear terms (directional)
        result += Vec3::from(sh.coeffs[1]) * 0.488603 * d.y;
        result += Vec3::from(sh.coeffs[2]) * 0.488603 * d.z;
        result += Vec3::from(sh.coeffs[3]) * 0.488603 * d.x;

        // Band 2: quadratic terms (more directional detail)
        result += Vec3::from(sh.coeffs[4]) * 1.092548 * d.x * d.y;
        result += Vec3::from(sh.coeffs[5]) * 1.092548 * d.y * d.z;
        result += Vec3::from(sh.coeffs[6]) * 0.315392 * (3.0 * d.z * d.z - 1.0);
        result += Vec3::from(sh.coeffs[7]) * 1.092548 * d.x * d.z;
        result += Vec3::from(sh.coeffs[8]) * 0.546274 * (d.x * d.x - d.y * d.y);

        result.max(Vec3::ZERO)
    }
}